### ISSUE TITLE
17.0.0.0 IP 段问题

### ISSUE THREAD

**Issue by huangyafei** [geekdada/create-surgio-store#9]
https://github.com/geekdada/create-surgio-store/blob/e3f051ce9f7caaebca3ae78f2ce803ec3c929e7c/template/template/clash.tpl#L62

17.0.0.0 不是苹果的 IP 段么，为什么在这里写在了 LAN 的规则下了啊？

**Comment by geekdada** [comment]
不出意外的话这个是抄来的…

我也觉得不太对…

**Comment by Smallthing** [comment]
因为这是apple用来做代理的段。
